server:
    port: 8081
spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-service
            auto-offset-reset: earliest
    datasource:
        url: jdbc:postgresql://localhost:5432/lessons
        username: app
        password: app
        jpa:
            hibernate:
                ddl-auto: update